export const ROUTES = {
  ADD_TRANSACTION: 'addTransactionScreen',
  LOGIN: 'loginScreen',
  SIGNUP: 'signUpScreen',
  PRESENTATION: 'presentationScreen',
  HOME: 'homeScreen',
  TRANSACTIONS: 'transictionScreen',
  USER: 'userScreen',
  CARD_DETAIL: 'cardDetailScreen',
  CARD_LIST: 'cardListScreen',
  ADD_CARD: 'addCardScreen',
  POUPP_TEACH: 'pouppTeachScreen',
  EXTRA_INCOME: 'extraIncomeScreen',
  POST_DETAIL: 'postDetailScreen',
  GOALS_LIST: 'goalsListScreen',
  GOAL_DETAIL: 'goalDetailScreen',
  ADD_GOAL: 'addGoalScreen',
  ADD_INCOME: 'addIncomeScreen',
  ACCOUNT_LIST: 'accountListScreen',
  SET_MOTIVATION: 'setMotivationScreen',
  INITIAL_BILLS: 'initialBillsScreen',
};
