export const ROUTES = {
  ADD_TRANSACTION: 'addTransactionScreen',
  LOGIN: 'loginScreen',
  SIGNUP: 'signUpScreen',
  PRESENTATION: 'presentationScreen',
  HOME: 'homeScreen',
  TRANSACTIONS: 'transictionScreen',
  USER: 'userScreen',
  CARD: 'cardScreen',
  POUPP_TEACH: 'pouppTeachScreen',
  EXTRA_INCOME: 'extraIncomeScreen',
  POST_DETAIL: 'postDetailScreen',
  GOALS_LIST: 'goalsListScreen',
  GOAL_DETAIL: 'goalDetailScreen',
};
